# Python animation

## Setup

### Define shape

In [1]:
import numpy as np

# Define original shape (triangle)
original_shape = np.array([
    [0, 0],
    [1, 0],
    [0.5, 1],
    [0, 0]  # Close the triangle
]).T  # Shape is 2xN

## Define helper for transformations

In [2]:
def get_transformation_matrix(
    scale: float,
    angle: float,
    tx: float,
    ty: float,
):
    '''Creates the transformation matrix for scaling, rotation, and translation.'''

    S = np.array([
        [scale, 0, 0],
        [0, scale, 0],
        [0, 0, 1]
    ])
    R = np.array([
        [np.cos(angle), -np.sin(angle), 0],
        [np.sin(angle), np.cos(angle), 0],
        [0, 0, 1]
    ])
    T = np.array([
        [1, 0, tx],
        [0, 1, ty],
        [0, 0, 1]
    ])
    return T @ R @ S

## Define animation parameters

In [3]:
num_frames = 60
angles = np.linspace(0, 2 * np.pi, num_frames)
scales = np.linspace(1, 2, num_frames)
translations = np.linspace(0, 5, num_frames)

## Animation

## Animation loop


In [4]:
for frame in range(num_frames):
    angle = angles[frame]
    scale = scales[frame]
    tx = translations[frame]
    ty = translations[frame]

    # Compute transformation matrix
    matrix = get_transformation_matrix(scale, angle, tx, ty)

    # Convert shape to homogeneous coordinates
    ones = np.ones((1, original_shape.shape[1]))
    shape_homogeneous = np.vstack((original_shape, ones))

    # Apply transformation
    transformed_shape = matrix @ shape_homogeneous

    if frame % 10 == 0:
        print(f"Transformation matrix for frame {frame+1}:\n{matrix}")
        print(f"Ones vector for homogeneous coordinates:\n{ones}")
        print(
            f"Shape coordinates (homogeneous) for frame {frame+1}:\n{shape_homogeneous}")
        print(
            f"Transformed shape coordinates (homogeneous) for frame {frame+1}:\n{transformed_shape}")
        print('-' * 50)

Transformation matrix for frame 1:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Ones vector for homogeneous coordinates:
[[1. 1. 1. 1.]]
Shape coordinates (homogeneous) for frame 1:
[[0.  1.  0.5 0. ]
 [0.  0.  1.  0. ]
 [1.  1.  1.  1. ]]
Transformed shape coordinates (homogeneous) for frame 1:
[[0.  1.  0.5 0. ]
 [0.  0.  1.  0. ]
 [1.  1.  1.  1. ]]
--------------------------------------------------
Transformation matrix for frame 11:
[[ 0.56667814 -1.02302801  0.84745763]
 [ 1.02302801  0.56667814  0.84745763]
 [ 0.          0.          1.        ]]
Ones vector for homogeneous coordinates:
[[1. 1. 1. 1.]]
Shape coordinates (homogeneous) for frame 11:
[[0.  1.  0.5 0. ]
 [0.  0.  1.  0. ]
 [1.  1.  1.  1. ]]
Transformed shape coordinates (homogeneous) for frame 11:
[[0.84745763 1.41413576 0.10776868 0.84745763]
 [0.84745763 1.87048564 1.92564977 0.84745763]
 [1.         1.         1.         1.        ]]
--------------------------------------------------
Transformation matrix for frame 21:
